config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  resources :projects do
    match "easy_issue_copy/setting", :to => "easy_issue_copy_setting#update", :via => [:post, :put, :patch]
    match "easy_issue_copy", :to => "easy_issue_copy_setting#post", :via => [:post, :put, :patch]
  end

  resources :issues do
    match "easy_issue_copy/link", :to => "issue_link#link", :via => [:post, :put, :patch]
  end
end

app/models/easy_issue_copy_issue_relation.rb
class EasyIssueCopyIssueRelation < ActiveRecord::Base
  unloadable

  validates :original_issue_id, uniqueness: {scope: :copied_issue_id}
end

app/models/easy_issue_copy_project_relation.rb
class EasyIssueCopyProjectRelation < ActiveRecord::Base
  unloadable
  belongs_to :internal_project, class_name: 'Project', foreign_key: 'project_id'
  belongs_to :external_project, class_name: 'Project', foreign_key: 'related_project_id'
end

app/controllers/easy_issue_copy_setting_controller.rb
class EasyIssueCopySettingController < ApplicationController
  unloadable
  before_filter :find_project

  def index
  end

  def update
    copy_source_project_id = params[:easy_issue_copy][:project_id]
    if copy_to_project = EasyIssueCopyProjectRelation.where(project_id: @project.id).first
      copy_to_project.update_attributes!(related_project_id: copy_source_project_id)
    else
      EasyIssueCopyProjectRelation.create!(
        project_id: @project.id,
        related_project_id: copy_source_project_id
      )
    end
    redirect_to :controller => 'projects', :action => "settings", :id => @project, :tab => 'easy_issue_copy'
  end

  private
  def find_project
    @project = Project.find(params[:project_id])
  rescue ActiveRecord::RecordNotFound
    render_404
  end
end

app/controllers/issue_link_controller.rb
class IssueLinkController < ApplicationController
  unloadable
  before_filter :find_issue
  before_filter :is_project_already_linked?

  def link
    @internal_issue.description = @internal_issue.description + "\n元チケット: \##{@external_issue.id}"
    @internal_issue.save!

    EasyIssueCopyIssueRelation.create!(
      original_issue_id: @external_issue.id,
      copied_issue_id: @internal_issue.id
    )

    flash[:notice] = "チケットを関連付けました。"
    redirect_to issue_path(params[:issue_id])
  end

  private
  def find_issue
    @internal_issue = Issue.find(params[:issue_id])
    @external_issue = Issue.find(params["easy_issue_copy"]["external_issue_id"])
  rescue ActiveRecord::RecordNotFound
    flash[:error] = "関連付けようとしているチケットが存在しません。"
    redirect_to issue_path(params[:issue_id])
    return false
  end

  def is_project_already_linked?
    @linked_project = EasyIssueCopyProjectRelation.where(
      project_id: @internal_issue.project_id,
      related_project_id: @external_issue.project_id
    )
    if @linked_project.empty?
      flash[:error] = "プロジェクトが関連していません。"
      redirect_to issue_path(params[:issue_id])
      return false
    end
  end

end

app/controllers/setting_controller.rb
class SettingController < ApplicationController
  unloadable
  before_filter :find_project

  def index
  end

  def update
    copy_source_project_id = params[:easy_issue_copy][:project_id]
    if copy_to_project = EasyIssueCopyProjectRelation.where(project_id: @project.id).first
      copy_to_project.update_attributes!(related_project_id: copy_source_project_id)
    else
      EasyIssueCopyProjectRelation.create!(
        project_id: @project.id,
        related_project_id: copy_source_project_id
      )
    end
    redirect_to :controller => 'projects', :action => "settings", :id => @project, :tab => 'easy_issue_copy'
  end

  private
  def find_project
    @project = Project.find(params[:project_id])
  rescue ActiveRecord::RecordNotFound
    render_404
  end 
end

app/helpers/setting_helper.rb
module EasyCopySettingHelper
end

app/views/easy_issue_copy/_copy_header.html.erb
<h2>外部プロジェクトから内部プロジェクトへコピー</h2>

app/views/easy_issue_copy/_form.html.erb
<% project_relation_to_internal = EasyIssueCopyProjectRelation.where(project_id: project.id).first %>
<% if project_relation_to_internal %>
  <% related_project_to_internal = project_relation_to_internal.internal_project %>
  <% related_project_users_to_internal = related_project_to_internal.members.map{|member| member.user_id} %>
  <% if related_project_to_internal && related_project_users_to_internal.include?(User.current.id) %>
    <%= hidden_field_tag 'issue[easy_issue_copy][original_issue_id]', params["original_issue_id"] %>
  <% end %>
<% end %>

app/views/easy_issue_copy/_show_link.html.erb
<div id="easy_issue_copy">
<% project_relation_to_internal = EasyIssueCopyProjectRelation.where(related_project_id: project.id).first %>
<% if project_relation_to_internal %>
  <% related_project_to_internal = project_relation_to_internal.internal_project %>
  <% related_project_users_to_internal = related_project_to_internal.members.map{|member| member.user_id} %>
  <% already_related_issue_to_internal = EasyIssueCopyIssueRelation.where(original_issue_id: issue.id.to_i).first %>
<% end %>

<% project_relation_to_external = EasyIssueCopyProjectRelation.where(project_id: project.id).first %>
<% if project_relation_to_external %>
  <% related_project_to_external = project_relation_to_external.external_project %>
  <% related_project_users_to_external = related_project_to_external.members.map{|member| member.user_id} %>
  <% already_related_issue_to_external = EasyIssueCopyIssueRelation.where(copied_issue_id: issue.id.to_i).first %>
<% end %>


<% if related_project_to_internal && related_project_users_to_internal.include?(User.current.id) && already_related_issue_to_internal %>
  <%= link_to '内部チケットを参照する', issue_path(id: already_related_issue_to_internal.copied_issue_id) %>
<% elsif related_project_to_internal && related_project_users_to_internal.include?(User.current.id) %>

<% options = {project_id: related_project_to_internal.id, easy_issue_copy: 1234, 'original_issue_id' => issue.id, 'issue[subject]' => issue.subject, 'issue[description]' => issue.description, 'issue[tracker_id]' => issue.tracker_id, 'issue[status_id]' => issue.status_id, 'issue[due_date]' => issue.due_date, 'issue[priority_id]' => issue.priority_id} %>
<% watcher_ids = issue.watchers.map(&:user_id) %>
<% duplicate_user_ids = related_project_users_to_internal.select{|u| watcher_ids.include?(u) } %>
<% duplicate_user_ids.each{|u| options['issue[watcher_user_ids][]'] = u } %>

  <%=link_to "外部チケットをコピーする", new_project_issue_path(options) %>

<% end %>
</div>

<% if related_project_to_external && related_project_users_to_external.include?(User.current.id) %>
  <% if already_related_issue_to_external %>
    <%= link_to("外部チケットを参照する", issue_path(id: already_related_issue_to_external.original_issue_id)) %>
  <% else %>
    <hr>
    <p>
      <div style='text-align: right;'><a href='#' id='easy_issue_copy_link_trigger' style='font-size: xx-small;'>外部プロジェクトのチケットと関連付け</a></div>
      <div id='easy_issue_copy_link_selecter' style='display: none;'>
      <%= form_tag issue_easy_issue_copy_link_path(issue.id) do %>
        関連付ける外部チケットのID
        <%= text_field_tag 'easy_issue_copy[external_issue_id]' %>
        <%= submit_tag "送信" %>
      <% end %>
      </div>
    </p>
    <hr>
    <script>
       $("#easy_issue_copy_link_trigger").click(function(){
         $("#easy_issue_copy_link_selecter").toggle();
       });
    </script>
  <% end %>
<% end %>

app/views/setting/_index.html.erb
コピーボタンを表示するコピー元のプロジェクトを選択
<% @project_relation = EasyIssueCopyProjectRelation.where(project_id: @project.id).first %>
<% @related_project = @project_relation ? Project.find(@project_relation.related_project_id) : EasyIssueCopyProjectRelation.new %>
<%= labelled_form_for :easy_issue_copy, @related_project, :url => project_easy_issue_copy_setting_path(@project) do |f| %>
  <p><%= select :easy_issue_copy, :project_id, project_tree_options_for_select(Project.where(Project.allowed_to_condition(User.current, :add_issues)), :selected => @related_project), :required => true %></p>

  <%= f.submit l(:button_update) %>
<% end %>